name: Release

on:
  push:
    tags:
      - '*.*.*-*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Pack sources
      run: |
        ARCHIVE_NAME="yyjson-nd-${GITHUB_REF_NAME}"
        tar czf ${ARCHIVE_NAME}.tar.gz --exclude=".git*" --exclude "*.rockspec" --transform="s,^,${ARCHIVE_NAME}/," -C src .
        envsubst < src/yyjson.rockspec > ${ARCHIVE_NAME}.rockspec
        zip ${ARCHIVE_NAME}.src.rock ${ARCHIVE_NAME}.rockspec ${ARCHIVE_NAME}.tar.gz

    - name: Publish artifacts
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.src.rock
