name: Release

on:
  push:
    tags:
      - '*.*.*-*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Pack sources and publish to Luarocks
      run: |
        ARCHIVE_NAME="yyjson-nd-${GITHUB_REF_NAME}"
        tar czf ${ARCHIVE_NAME}.tar.gz --exclude=".git*" --exclude "*.rockspec" --transform="s,^,${ARCHIVE_NAME}/," -C src .
        envsubst < src/yyjson-nd.rockspec > ${ARCHIVE_NAME}.rockspec
        zip ${ARCHIVE_NAME}.src.rock ${ARCHIVE_NAME}.rockspec ${ARCHIVE_NAME}.tar.gz
        sudo apt-get update && sudo apt-get install luarocks
        yyjson-nd-0.1.2-1.linux-x86_64.rock
        luarocks build --pack-binary-rock ${ARCHIVE_NAME}.src.rock
        luarocks upload ${ARCHIVE_NAME}.rockspec ${ARCHIVE_NAME}.src.rock --api-key ${LUAROCKS_TOKEN}

    - name: Publish artifacts
      uses: softprops/action-gh-release@v2
      with:
        files: |
          yyjson-nd-*.linux-x86_64.rock
          yyjson-nd-*.tar.gz
          yyjson-nd-*.src.rock
