name: Release

on:
  push:
    tags:
      - '*.*.*-*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        path: src

    - name: Pack sources
      run: |
        ARCHIVE_NAME="yyjson-nd-${GITHUB_REF_NAME}"
        tar czf ${ARCHIVE_NAME}.tar.gz --exclude=".git*" --exclude "*.rockspec" --transform="s,^,${ARCHIVE_NAME}/," -C src .

    - name: Publish sources
      uses: softprops/action-gh-release@v2
      with:
        files: |
          yyjson-nd-*.tar.gz

    - name: Publish to Luarocks
      run: |
          ARCHIVE_NAME="yyjson-nd-${GITHUB_REF_NAME}"
          envsubst < src/yyjson-nd.rockspec > ${ARCHIVE_NAME}.rockspec
          sudo apt-get -q update && sudo apt-get -qy install lua-json luarocks
          luarocks pack ${ARCHIVE_NAME}.rockspec
          luarocks build --pack-binary-rock ${ARCHIVE_NAME}.src.rock
          luarocks upload ${ARCHIVE_NAME}.rockspec ${ARCHIVE_NAME}.src.rock --api-key ${{ secrets.LUAROCKS_TOKEN }}

    - name: Publish packs
      uses: softprops/action-gh-release@v2
      with:
        files: |
          yyjson-nd-*.linux-x86_64.rock
          yyjson-nd-*.src.rock